#ifndef DEFINES_HPP
#define DEFINES_HPP

#define DEBUG true
#define BAUDRATE 4800

#define WHEELS_M1_FLT 33
#define WHEELS_M1_PWM 8
#define WHEELS_M1_SLP 30
#define WHEELS_M1_DIR 25
#define WHEELS_M1_CS A15
#define WHEELS_M2_FLT 31
#define WHEELS_M2_PWM 7
#define WHEELS_M2_SLP 32
#define WHEELS_M2_DIR 23
#define WHEELS_M2_CS A14

#define WHEEL_MIN_SPEED 0
#define WHEEL_MAX_SPEED 400

#define WHEELS_M1_ENCA 20
#define WHEELS_M1_ENCB 21
#define WHEELS_M2_ENCA 2
#define WHEELS_M2_ENCB 3

// TODO: Add arm definitions
#define ARM_BASE_PIN 12
#define ARM_SHOULDER_PIN 11
#define ARM_WRIST_PIN 10
#define ARM_GRIPPER_PIN 9

// Not Used
// #define ARM_SHOULDER_FEEDBACK_PIN A2
// #define ARM_WRIST_FEEDBACK_PIN A0
// #define ARM_GRIPPER_FEEDBACK_PIN A1

#define ARM_BASE_MIN 440
#define ARM_BASE_MAX 2238
#define ARM_SHOULDER_MIN 440
#define ARM_SHOULDER_MAX 2400
#define ARM_WRIST_MIN 440
#define ARM_WRIST_MAX 2400
#define ARM_GRIPPER_MIN 440
#define ARM_GRIPPER_MAX 1408

#define LCD_SCREEN_RS_PIN 42
#define LCD_SCREEN_E_PIN 43
#define LCD_SCREEN_D4_PIN 44
#define LCD_SCREEN_D5_PIN 45
#define LCD_SCREEN_D6_PIN 46
#define LCD_SCREEN_D7_PIN 47

#define PHOTOTRANSISTOR_PIN A13
#define PHOTOTRANSISTOR_THRESHOLD 15

// TODO: Define start button pin
#define START_BUTTON_PIN 999

#endif // DEFINES_HPP
